site_name: Connect Four Lab Documentation
theme: 'material'
# theme_dir: theme
docs_dir: sources

markdown_extensions:
  - codehilite
  
pages:
- Home: index.md
- Getting Started: gettingStarted.md
- LICENSE: license.md
- Game:
  - Game: Game/game.md
  - Timer: Game/timer.md
  - Helpers: Game/helpers.md
- Agents:
  - Base class: Agents/base.md
  - Trainers: Agents/trainers.md
  - List of Agents: Agents/agents.md
  - List of Strategies: Agents/strategies.md
- Custom Widgets:
  - Selection Box: CustomWidgets/selectionBox.md
  - Confirmation Pop-up: CustomWidgets/confirmationPopUp.md
  
